package com.techelevator;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/*This program generates a random list of vehicles (between 10 and 20 vehicles) then assigns a random number 
of miles for each vehicle (between 10 and 240 miles) and calculates the toll amount for each vehicle and total toll.*/

public class TollBoothMainProgram {

	public static void main(String[] args) {

		Random randomForNumberOfVehicls = new Random(); // used to generate a random number of vehicles
		int numberOfVehicls = randomForNumberOfVehicls.nextInt(10) + 10; // holds a random number of vehicles(between 10
																			// and 20 inclusive)
		int totalNumberOfMiles = 0; // total number of miles traveled by all vehicles
		double totalRevenue = 0; // total number of revenue generated by all vehicles

		DecimalFormat formatter = new DecimalFormat("#,##0.00"); // used to format and display currency

		List<Vehicle> allCars = new ArrayList<Vehicle>(); // list that holds all vehicles traveled thru toll booth

		// this loop generates a random type of vehicle and pushes the vehicle into the
		// list of vehicles
		for (int i = 0; i < numberOfVehicls; i++) {
			Random randForTypeOfVehicle = new Random();
			int typeOfCar = randForTypeOfVehicle.nextInt(3) + 1;

			if (typeOfCar == 1) {
				Truck truck = new Truck();
				allCars.add(truck);
			} else if (typeOfCar == 2) {
				Car car = new Car();
				allCars.add(car);
			} else if (typeOfCar == 3) {
				Tank tank = new Tank();
				allCars.add(tank);
			}
		}

		System.out
				.println("This program generates a random list of vehicles (between 10 and 20 vehicles) then assigns a"
						+ " random number \nof miles for each vehicle (between 10 and 240 miles) and calculates the toll amount for each vehicle and total toll.\n\n");

		System.out.printf("%-22s %-20s %-1s  \n", "Vehicle", "Distance Traveled", "Toll $");
		System.out.println("**************************************************");
		// this loop goes thru each vehicle in the list and calculates the tall they
		// have to pay and displays: the type of vehicle, the miles traveled, and
		// revenue collected
		for (Vehicle eachCar : allCars) {
			Random random = new Random();
			int distance = random.nextInt(230) + 10;
			totalNumberOfMiles += distance;
			eachCar.calculateToll(distance);
			totalRevenue += eachCar.getToll();

			System.out.printf("%-22s %-20s %-1s %-1s  \n", eachCar.getTypeOfVehicle(), distance, "$",
					(formatter.format(eachCar.getToll())));

		}
		// displaying the total miles traveled by all vehicles and total revenue
		// collected from all vehicles
		System.out.println("**************************************************");
		System.out.println("Total number of cars: " + allCars.size());
		System.out.println("Total number of miles: " + totalNumberOfMiles);
		System.out.println("Total revenue: $" + (formatter.format(totalRevenue)));

	}

}
